apiVersion: apps/v1
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cs6065-python-deployment
  labels:
    app: cs6065-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cs6065-python
  template:
    metadata:
      labels:
        app: cs6065-python
    spec:
      containers:
      - name: cs6065-python
        image: cs6065-python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
